### ISSUE TITLE
Spaces in markdown

### ISSUE THREAD

**Issue by vedicastrology123** [philhawksworth/netlify-plugin-minify-html#13]
The space around links in markdown are removed.

Go to [this is a link](/link/page) page.

The space after 'Go to' is removed and before 'page' - in the html generated.

**Comment by xplosionmind** [comment]
Same here. [Check this page](https://tommi.space/data)

**Comment by shanerobinson** [comment]
Same here. Was also reported on the html-minifier repo 2 days ago: https://github.com/kangax/html-minifier/issues/1082

**Comment by DavidBiddle** [comment]
I believe this is the same underlying issue as #8  - configuring your netlify.toml to set `collapseInlineTagWhitespace = false` should resolve it. If you don't have a netlify.toml there's [a good example config](https://github.com/philhawksworth/netlify-plugin-minify-html/issues/8#issuecomment-669350451) on that issue.
