### ISSUE TITLE
spaces before <em> and after </em>

### ISSUE THREAD

**Issue by johanvanmol** [philhawksworth/netlify-plugin-minify-html#18]
Hi, I recently started using this plugin on https://www.oefenroutes.be.
Unfortunately, it strips away spaces when using <em> tags:

Before: `voor <em>Examencentrum Deurne</em> vinden`

Becomes: 

After: `voor<em>Examencentrum Deurne</em>vinden`

![afbeelding](https://user-images.githubusercontent.com/820474/106365369-727ad080-6335-11eb-856a-6a8bef0e2d49.png)

**Comment by DavidBiddle** [comment]
I believe this is the same underlying issue as #8  - configuring your netlify.toml to set `collapseInlineTagWhitespace = false` should resolve it. If you don't have a netlify.toml there's [a good example config](https://github.com/philhawksworth/netlify-plugin-minify-html/issues/8#issuecomment-669350451) on that issue.

**Comment by johanvanmol** [comment]
Hi David, thank you for pointing me in the right direction.  This resolved my issue.
