### ISSUE TITLE
Removes space surrounding links

### ISSUE THREAD

**Issue by ItaiAxelrad** [philhawksworth/netlify-plugin-minify-html#8]
The plugin appears to remove white space surrounding link tags. This results in what looks like a concatenated string with the link text in the middle.

**Comment by Lukasvo** [comment]
I see this too. Disabling the plugin because of this.

**Comment by philhawksworth** [comment]
Under the hood, this plugin uses this [html-minifier](https://github.com/kangax/html-minifier)

You can pass it various [configurations in the netlify.toml](https://github.com/philhawksworth/netlify-plugin-minify-html#2-add-the-plugin-and-its-options-to-your-netlifytoml). Perhaps there is a corresponding option here which will resolve that?

https://github.com/kangax/html-minifier#options-quick-reference

**Comment by hlorand** [comment]
Add the following code in a `netlify.toml` file in your repository root to override default settings:

```
[[plugins]]
  package = "netlify-plugin-minify-html"

  [plugins.inputs]
    contexts = [
      'production',
      'branch-deploy',
      'deploy-preview'
    ]

  [plugins.inputs.minifierOptions]
    collapseInlineTagWhitespace = false
```

**Comment by philhawksworth** [comment]
This is actually what is shown as the example in the readme for this plugin.
If this setting does resolve things for you @ItaiAxelrad,  I'll close this issue.

**Comment by ItaiAxelrad** [comment]
It does resolve the issue, my apologies for not seeing that earlier!

**Comment by philhawksworth** [comment]
Hooray!
Thanks @ItaiAxelrad.
